const ActionType = {
    REQ_GET_USER: 'REQ_GET_USER',
    RES_GET_USER: 'RES_GET_USER',

    REQ_ADD_USER: 'REQ_ADD_USER',
    RES_ADD_USER: 'RES_ADD_USER',

    REQ_DEL_USER: 'REQ_DEL_USER',
    RES_DEL_USER: 'RES_DEL_USER',

    REQ_UPDATE_USER: 'REQ_UPDATE_USER',
    RES_UPDATE_USER: 'RES_UPDATE_USER',


    GET_PRODUCT: 'GET_PRODUCT',
    ADD_PRODUCT: 'ADD_PRODUCT',
    DEL_PRODUCT: 'DEL_PRODUCT',
    UPDATE_PRODUCT: 'UPDATE_PRODUCT',

    GET_PRODUCTCAT : 'GET_PRODUCTCAT'
}

export default ActionType