export const company = [
    {
      namaCompany: "Senior Digital Marketing Indorama",
      loc: "Jakarta",
      expe: "3-5 Tahun",
      freq: "Actively Hiring",
      lastmod: "Dibuat 1 hari lalu",
    },
    {
      namaCompany: "Java Developer PT Codeid",
      loc: "Jakarta",
      expe: "1-2 Tahun",
      freq: "Actively Hiring",
      lastmod: "Dibuat 3 hari lalu",
    },
    {
      namaCompany: "Javascript Developer PT Codeid",
      loc: "Jakarta",
      expe: "2 Tahun",
      freq: "Actively Hiring",
      lastmod: "Dibuat 1 hari lalu",
    },
    {
      namaCompany: "Javascript2 Developer PT Codeid",
      loc: "Jakarta",
      expe: "2 Tahun",
      freq: "Actively Hiring",
      lastmod: "Dibuat 1 hari lalu",
    },
    {
        namaCompany: "Javascript3 Developer PT Codeid",
        loc: "Jakarta",
        expe: "2 Tahun",
        freq: "Actively Hiring",
        lastmod: "Dibuat 1 hari lalu",
      },
      {
        namaCompany: "Javascript4 Developer PT Codeid",
        loc: "Jakarta",
        expe: "2 Tahun",
        freq: "Actively Hiring",
        lastmod: "Dibuat 1 hari lalu",
      },
      {
        namaCompany: "Javascript5 Developer PT Codeid",
        loc: "Jakarta",
        expe: "2 Tahun",
        freq: "Actively Hiring",
        lastmod: "Dibuat 1 hari lalu",
      },
      {
        namaCompany: "Javascript6 Developer PT Codeid",
        loc: "Jakarta",
        expe: "2 Tahun",
        freq: "Actively Hiring",
        lastmod: "Dibuat 1 hari lalu",
      },
      {
        namaCompany: "Javascript7 Developer PT Codeid",
        loc: "Jakarta",
        expe: "2 Tahun",
        freq: "Actively Hiring",
        lastmod: "Dibuat 1 hari lalu",
      },
      {
        namaCompany: "Javascript8 Developer PT Codeid",
        loc: "Jakarta",
        expe: "2 Tahun",
        freq: "Actively Hiring",
        lastmod: "Dibuat 1 hari lalu",
      },
      {
        namaCompany: "Javascript9 Developer PT Codeid",
        loc: "Jakarta",
        expe: "2 Tahun",
        freq: "Actively Hiring",
        lastmod: "Dibuat 1 hari lalu",
      },
  ];