const ActionType = {
  REQ_GET_USER: "REQ_GET_USER",
  RES_GET_USER: "RES_GET_USER",

  REQ_ADD_USER: "REQ_ADD_USER",
  RES_ADD_USER: "RES_ADD_USER",

  REQ_DEL_USER: "REQ_DEL_USER",
  RES_DEL_USER: "RES_DEL_USER",

  REQ_UPDATE_USER: "REQ_UPDATE_USER",
  RES_UPDATE_USER: "RES_UPDATE_USER",

  //product

  REQ_GET_PRODUCT: "REQ_GET_PRODUCT",
  RES_GET_PRODUCT: "RES_GET_PRODUCT",

  REQ_ADD_PRODUCT: "REQ_ADD_PRODUCT",
  RES_ADD_PRODUCT: "RES_ADD_PRODUCT",

  REQ_DEL_PRODUCT: "REQ_DEL_PRODUCT",
  RES_DEL_PRODUCT: "RES_DEL_PRODUCT",

  REQ_UPDATE_PRODUCT: "REQ_UPDATE_PRODUCT",
  RES_UPDATE_PRODUCT: "RES_UPDATE_PRODUCT",

  //product cat
  REQ_GET_PRODUCT_CAT: "REQ_GET_PRODUCT_CAT",
  RES_GET_PRODUCT_CAT: "RES_GET_PRODUCT_CAT",

  REQ_ADD_PRODUCT_CAT: "REQ_ADD_PRODUCT_CAT",
  RES_ADD_PRODUCT_CAT: "RES_ADD_PRODUCT_CAT",

  REQ_DEL_PRODUCT_CAT: "REQ_DEL_PRODUCT_CAT",
  RES_DEL_PRODUCT_CAT: "RES_DEL_PRODUCT_CAT",

  REQ_UPDATE_PRODUCT_CAT: "REQ_UPDATE_PRODUCT_CAT",
  RES_UPDATE_PRODUCT_CAT: "RES_UPDATE_PRODUCT_CAT",

  REQ_GET_LOGIN : "REQ_GET_LOGIN",
  RES_GET_LOGIN : "RES_GET_LOGIN"
};

export default ActionType;
